services:
  keenetic_gist_backup:
    container_name: keenetic-gist-backup
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    network_mode: host
    restart: unless-stopped
    environment:
      - KEENETIC_URL
      - KEENETIC_USERNAME
      - KEENETIC_PASSWORD
      - GITHUB_TOKEN
      - GIST_DESCRIPTION
      - SCHEDULE